config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  

  root 'site#index'
    get '/vendor/:date' => 'vendors#index'
        get '/vendors' => 'vendors#show'
        get '/vendors/examineevent/:id' => 'vendors#examine_event'
        get '/vendor/events/servicing' => 'vendors#servicing'
        

    get '/organizer/:date' => 'organizers#index'
      
      get '/organizers/addevent' => 'organizers#new' 
      post '/organizers/addevent' => 'organizers#create'
      get '/organizers/showevent/:id' => 'organizers#event_show', as: :organizers_event
      delete 'organizer/deleteevent/:id' => 'organizers#event_delete'
      get '/organizers/examinevendor/:id' => 'organizers#examine_vendor'
      get '/organizers/:id' => 'organizers#show'
    get '/staff' => 'staff#index'
  get '/api/events/:id/comments' => 'api#get_comments'
  post '/api/events/:id/comments' => 'api#add_comments', as: :add_comment
  post '/api/events/:id/comments/redact' => 'api#redact'
  get '/api/vendors/vendorinfo/:id' => 'api#vendor_info'
  delete '/api/event/:id/deleteconfirmedservice/:service_id' => 'api#delete_confirmed_service'
  post '/api/event/confirm/:id' => 'api#confirm_event'
  post '/api/events/addservice' => 'api#add_service'
  get '/api/messages/unread_count/:id' => 'api#unread_get'
  get '/api/messages/confirm_all/:id' => "api#confirm_all"
  get '/api/events/:id/check_confirmed' => 'api#check_confirmed'

  get '/profiles/:id' => 'profiles#show', as: :profile
  put '/profiles/:id' => 'profiles#update'

  post '/api/message/send_confirmation' => 'api#send_confirmation'
  get '/api/message/:id/messages' => 'api#serve_messages'
  get '/api/messages/confirm_read' => 'api#confirm_messages'
  get '/calendar' => 'api#calendar', as: :calendar
  get '/api/events/calendar_get' => 'api#send_events'

  

end

app/controllers/vendors_controller.rb
class VendorsController < ApplicationController
	before_action(:authenticate_user!)
	 def show
	 	@organizers = User.where(role: "organizer")
	 	@events = Event.all
	 	render 'show'
	 end
	def index
		@organizers = User.where(role: "organizer")
		@vendors = User.where(:role => 'vendor')
		date = Date.parse(params[:date])
		searchDate = DateTime.new(date.year, date.month, date.day)
		@events = Event.all.where('start_date BETWEEN ? AND ?', searchDate.beginning_of_day, searchDate.end_of_day).all
		@date = date
		render 'index'
	end
	def examine_event
		@event = Event.find_by(:id => params[:id])
		@organizer = User.find_by(:id => @event.user_id)
		render 'examineevent'
	end
	def servicing
		@organizers = User.where(role: "organizer")
		@vendors = User.where(:role => 'vendor')
		@events = current_user.events_scheduled(current_user.id)
		render 'confirmed_events'
		
	end


 
end

app/helpers/vendors_helper.rb
module VendorsHelper
	def pretty_date(date)
		return date.strftime("%B %-d, %Y at %l:%M ")
	end
	def pretty_date2(date)
		return date.strftime("%B %-d, %Y")
	end
end

app/views/vendors/confirmed_events.html.erb
<style>
	.label-edit {
		position: absolute;
		top: 15px;
		right: 28px;
	}
</style>
<div class="container-fluid wow fadeInLeft animated">

	
	
	<div class="col-lg-12">

		<div class="row">
			<div class="col-xl-8 col-lg-8 col-md-8 col-sm-8" >
				<h1>Confirmed Events</h1>
			</div>
			<div class="col-xl-4 col-lg-4 col-md-4 col-sm-4">
			<br>
        <ul class="list-unstyled list-inline pull-left">
          <li><a href="<%= calendar_path  %>" class= "btn btn-primary btn-md"style="color:white;">Back to Calendar</a></li>
        </ul>
			</div>
		</div>
	<hr>
	<br>
		<% if @events.present? %>
			<% @events.each do |event| %>
				<div class="col-lg-3" style="position:relative;">
					<a href="/vendors/examineevent/<%= event.id %>" style='color:black;'>
						<div class="panel panel-default panel-border-grey ex1 text-center">
							<div class="panel-body">
								<% servicing = false %>
								<% event.confirmed_services.each do |serv| %>
									<% association = AssociatedService.find_by(:id => serv.associated_service_id) %>
									<% if association.service_id = current_user.id %>
										<% servicing = true %>
									<% end %>
								<% end %>
								<h4><%= event.name  %> <br> <small><%= event.venue  %></small></h4> <% if servicing == true%>
								<span class="label label-success label-edit">Servicing</span>
								<style> .ex1 {background-color: rgba(92,184,92,0.2)}</style>
								<% end %>
								<hr>
								Posted by: <%= User.find_by(:id => event.user_id).first_name  %> <%= User.find_by(:id => event.user_id).last_name  %><br>
								Start time: <%= pretty_date(event.start_date)  %> <br>
								
								<%= event.city  %>, <%= event.state  %> <br>
								<%= event.address %>
								<%= event.zipcode  %>
							</div>
						</div>
					</a>
				</div>
			<% end %>
			<% else %>
							<h2>Whoopss...
									<small>There are no events for this date.</small>
							</h2>
		<% end %>
	</div>
</div>


<div class="modal fade" id="organizersModal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Organizers In Your Area</h4>
      </div>
      <div class="modal-body">
     	<ul class="list-unstyled">
			<% @organizers.each do |organizer|  %>
				<li>
				<h4 style="display: inline"><a href="<%= profile_path(organizer.id)  %>" ><b><%= organizer.first_name  %> <%= organizer.last_name  %></b></a></h4>
				</li>
				<hr>
			<%  end %>
		</ul>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/vendors/examineevent.html.erb
<div class="container-fluid wow fadeInLeft animated">

	 
	<div class="col-lg-11 center-block">
	<br>
	<div class="panel panel-default  panel-border-black">
			<div class="panel-body">
				<div class="row">
						<div class="col-md-10" >
						<h3>Details for <span class='highlight'><b><a href="https://www.google.com/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=<%= @event.name%>"><%= @event.name %></a></b></span></h3>	
						</div>
						<div class="col-md-2">
							<ul class="list-inline">
								<a class="btn btn-primary" href="<%= calendar_path  %>">Back to calendar</a>
							</ul>
						</div>
					</div>
					<hr>
				<div class="col-md-6">
					<p> 
						<h4>Organizer: <a href="/profiles/<%= @organizer.id%>"><%= @organizer.name %></a></h4>
						
						<h4>Start time: <%= pretty_date(@event.start_date)  %></h4> 
						<% if @event.end_date != nil %>
							<h4>End time: <%= pretty_date(@event.end_date)  %></h4> 
						<% end %>
						<h4>City: <%= @event.city  %>, <%= @event.state  %></h4> 
						<h4>Address: <%= @event.address %></h4>
						<h4>Zipcode: <%= @event.zipcode  %></h4>
						<h4>Guest Count: <%= @event.guestcount.to_s  %></h4>
					</p>
					<br>
					<hr>
					<button  data-toggle="modal" data-target="#myModal" class="btn btn-default">
						View Service providers
					</button>
					<% unless @event.confirmed %>
					<%= link_to 'Offer my services!', add_comment_path( :text => 'My company would like to offer our services for this event!'), data: { :confirm => 'Are you sure?', method: :post, toggle: :tab }, remote: true , :class => "btn btn-sm btn-success btn-edit offer offerbtn", :style =>"z-index: 30;", :id => @event.id   %>
					<script>
					function checkForFalse(){
						console.log('initiated')
						$.get('/api/events/'+<%= @event.id %>+'/check_confirmed', handleResponse)

						function handleResponse(data){
							if (data.response === "confirmed") {
								$('.offerbtn').addClass('disabled')
								$('.offerbtn').removeClass('btn-success')
								$('.offerbtn').addClass('btn-danger')
								$('.offerbtn').text('Event Confirmed')
								setTimeout(function(){location.reload();}, 2000)
							}
						}
					}
					setInterval(checkForFalse, 2000)
					</script>
					<% end %>
				</div>
				
				<style>
				.nav-tabs>li>a {
					padding: 10px;
				}
				.nav-tabs>li.active>a, .nav-tabs>li.active>a:hover, .nav-tabs>li.active>a:focus {
					background-color:#0E8FAB;
					color: white;
				}
				</style>
				<div class="col-md-6">
						<ul class="nav nav-tabs" role="tablist">
							<li role="presentation" class="active"><a href="#comments" aria-controls="comments" role="tab" data-toggle="tab">Comments</a></li>
						  	<li role="presentation" ><a href="#map" aria-controls="map" role="tab" data-toggle="tab">Map</a></li>
						 </ul>

					  <!-- Tab panes -->
					  <div class="tab-content">
					   <div role="tabpanel" class="tab-pane" id="map">
					    	<img src="https://maps.googleapis.com/maps/api/staticmap?markers=color:red%7Clabel:S%7C<%= @event.address%>&size=600x300&maptype=roadmap&zoom=15" class="img img-thumbnail">
					    </div>
					    <div role="tabpanel" class="tab-pane active" id="comments">
					    	<div id="commentList">
								<div class="react_comments">
									<%= react_component('CommentBox', props = {:url => "/api/events/#{@event.id}/comments", :pollInterval => 1000}) %>
								</div>	
							</div>
					    </div>
					  </div>
					</div>
				</div>
			</div>
		</div>
			
	</div>
	
</div>
	
</div>


<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Service providers schdeduled for <%= @event.name  %></h4>
      </div>
      <div class="modal-body">
      	<%if @event.confirmed_services.count < 1 %>
      		<p>
      			This event has yet to schedule any services. Offer your services through the comments tab or by clicking on offer my service!
      		</p>
      	<% end %>
      		<% @event.confirmed_services.each do |serv| %>
      			<p class="lead">
	      				
	      					<% association = AssociatedService.find_by(:id => serv.associated_service_id) %>
	      					<img src="<%= User.find_by(:id => association.user_id).profile.imageurl%>" class="img img-thumbnail" width="10%">
	      					<%= Service.find_by(:id => association.service_id).name  %> 
							<span class="highlight"> <a href='/profiles/<%= association.user_id%>'><%= User.find_by(:id => association.user_id).profile.name  %></a> </span>
	      					
	      					
	      			
	      			</p>
      		<% end %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

app/views/vendors/index.html.erb
<style>
	.label-edit {
		position: absolute;
		top: 15px;
		right: 28px;
	}
</style>
<div class="container-fluid wow fadeInLeft animated">

	
	
	<div class="col-lg-12">

		<div class="row">
			<div class="col-xl-8 col-lg-8 col-md-8 col-sm-8" >
				<h1>Event's for <%= pretty_date2(@date)%></h1>
			</div>
			<div class="col-xl-4 col-lg-4 col-md-4 col-sm-4">
			<br>
        <ul class="list-unstyled list-inline pull-left">
          <li><a href="<%= calendar_path  %>" class= "btn btn-primary btn-md"style="color:white;">Back to Calendar</a></li>
        </ul>
			</div>
		</div>
	<hr>
	<br>
		<% if @events.present? %>
			<% @events.each do |event| %>
				<div class="col-lg-3" style="position:relative;">
					<a href="/vendors/examineevent/<%= event.id %>" style='color:black;'>
						<div class="panel panel-default panel-border-grey ex1 text-center">
							<div class="panel-body">
								<% servicing = false %>
								<% event.confirmed_services.each do |serv| %>
									<% association = AssociatedService.find_by(:id => serv.associated_service_id) %>
									<% if association.service_id = current_user.id %>
										<% servicing = true %>
									<% end %>
								<% end %>
								<h4><%= event.name  %> <br> <small><%= event.venue  %></small></h4> <% if servicing == true%>
								<span class="label label-success label-edit">Servicing</span>
								<style> .ex1 {background-color: rgba(92,184,92,0.2)}</style>
								<% end %>
								<hr>
								Posted by: <%= User.find_by(:id => event.user_id).first_name  %> <%= User.find_by(:id => event.user_id).last_name  %><br>
								Start time: <%= pretty_date(event.start_date)  %> <br>
								<% if event.end_date.present? %>
									End time: <%= pretty_date(event.end_date)  %> <br>
								<% end %>
								<%= event.city  %>, <%= event.state  %> <br>
								<%= event.address %>
								<%= event.zipcode  %>
							</div>
						</div>
					</a>
				</div>
			<% end %>
			<% else %>
							<h2>Whoopss...
									<small>There are no events for this date.</small>
							</h2>
		<% end %>
	</div>
</div>


<div class="modal fade" id="organizersModal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title">Organizers In Your Area</h4>
      </div>
      <div class="modal-body">
     	<ul class="list-unstyled">
			<% @organizers.each do |organizer|  %>
				<li>
				<h4 style="display: inline"><a href="<%= profile_path(organizer.id)  %>" ><b><%= organizer.first_name  %> <%= organizer.last_name  %></b></a></h4>
				</li>
				<hr>
			<%  end %>
		</ul>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->